I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/script.rpy", line 74, in script call
    call chap5
  File "game/scripts/chapter5.rpy", line 7, in script
    show sandy center
Exception: Image 'sandy' does not accept attributes 'center'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/script.rpy", line 74, in script call
    call chap5
  File "game/scripts/chapter5.rpy", line 7, in script
    show sandy center
  File "/Volumes/renpy-8.2.0-sdk/renpy-8.2.0-sdk/renpy/ast.py", line 1113, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/Volumes/renpy-8.2.0-sdk/renpy-8.2.0-sdk/renpy/ast.py", line 1076, in show_imspec
    renpy.config.show(name,
  File "/Volumes/renpy-8.2.0-sdk/renpy-8.2.0-sdk/renpy/exports.py", line 739, in show
    if not base.find_target() and renpy.config.missing_show:
  File "/Volumes/renpy-8.2.0-sdk/renpy-8.2.0-sdk/renpy/display/image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "/Volumes/renpy-8.2.0-sdk/renpy-8.2.0-sdk/renpy/display/displayable.py", line 246, in _duplicate
    args.extraneous()
  File "/Volumes/renpy-8.2.0-sdk/renpy-8.2.0-sdk/renpy/display/displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'sandy' does not accept attributes 'center'.

macOS-13.4-arm64-arm-64bit arm64
Ren'Py 8.2.0.24012702
dreamscapes 1.0
Thu Mar 28 21:48:23 2024
