I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/gui.rpy", line 96, in script
    define gui.main_menu_background = main_menu_animated
  File "game/gui.rpy", line 96, in script
    define gui.main_menu_background = main_menu_animated
  File "game/gui.rpy", line 96, in <module>
    define gui.main_menu_background = main_menu_animated
NameError: name 'main_menu_animated' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Users/oliviamei/Downloads/renpy-8.1.3-sdk/renpy/bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "/Users/oliviamei/Downloads/renpy-8.1.3-sdk/renpy/main.py", line 564, in main
    renpy.game.context().run(node)
  File "game/gui.rpy", line 96, in script
    define gui.main_menu_background = main_menu_animated
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 444, in raise_
  File "game/gui.rpy", line 96, in script
    define gui.main_menu_background = main_menu_animated
  File "/Users/oliviamei/Downloads/renpy-8.1.3-sdk/renpy/ast.py", line 2508, in execute
    self.set()
  File "/Users/oliviamei/Downloads/renpy-8.1.3-sdk/renpy/ast.py", line 2522, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "/Users/oliviamei/Downloads/renpy-8.1.3-sdk/renpy/python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/gui.rpy", line 96, in <module>
    define gui.main_menu_background = main_menu_animated
NameError: name 'main_menu_animated' is not defined

macOS-14.0-arm64-arm-64bit arm64
Ren'Py 8.1.3.23091805
test 1.0
Mon Feb  5 17:34:34 2024
